Added the four main Glyph categories and updated the README file
SynBioDex/SBOL-visual pull request #106
Opened 2020-10-02 10:33 UTC by goksel

2020-10-02 11:03 UTC, jakebeal commented on Ontology/v2/sbol-vo.rdf
> -          <owl:someValuesFrom rdf:resource="http://identifiers.org/sbo/SBO:0000169"/>
This change seems to have removed all of the SBO restrictions for interactions; we don't want to lose that.

2020-10-02 11:04 UTC, jakebeal requested changes
SBO restrictions appear to have been lost for interactions.

2020-10-02 11:04 UTC, jakebeal commented on Ontology/v2/sbol-vo.rdf
> -          <owl:someValuesFrom rdf:resource="http://identifiers.org/sbo/SBO:0000169"/>
The same is the case for all of the other interactions

2020-10-02 13:08 UTC, jakebeal commented
Note: addressing #96

2020-11-29 16:14 UTC, goksel commented
@jakebeal Please check merge the pull request https://github.com/SynBioDex/SBOL-visual/pull/133.

2020-11-29 17:56 UTC, jakebeal commented
I've added a comment on #133, and am waiting for your response there.

Can this one be closed as obsolete?

2020-12-01 01:10 UTC, jakebeal commented
Superseded by #133. @goksel , can you delete the branch if it is no longer needed?

2020-12-01 01:10 UTC, closed without merging