README files update for Glyphs - Issue 15
SynBioDex/SBOL-visual pull request #72
Opened 2019-09-23 13:45 UTC by goksel

I updated the readme files to fix issues listed here: https://github.com/SynBioDex/SBOL-visual/issues/15

I believe all six issue are now fixed. 

EXCEPT:
The actual PNG glyphs for 3' overhang and sticky restriction sites STILL need to be created. The readme files were created correctly using the proper file names. Once the PNG files are replaced, this issue can be closed.

2019-09-24 19:00 UTC, jakebeal commented
I've changed the target from master to a new branch, in order to allow resolution of the last issues before merging into master.

2019-09-24 19:09 UTC, jakebeal requested changes

2019-09-24 19:09 UTC, jakebeal commented on Glyphs/FunctionalComponents/complex/README.md
> +![glyph specification](complex-ps-specification.pngs
This is now creating a broken link --- I assume the change is accidental?

2019-09-24 19:12 UTC, jakebeal approved these changes

2019-09-24 19:12 UTC, merged

2019-09-24 19:13 UTC, jakebeal commented
I'm now going to finish the last bits in the ontology-update branch

2019-09-25 13:20 UTC, goksel commented
Thanks @jakebeal, I must have introduced the typo as a mistake somehow.